/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.glass.events.KeyEvent;
import java.awt.Toolkit;
import main_system.Sistema;
import java.io.IOException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ikaro
 */
public class LoginFrame extends javax.swing.JFrame {
    
    private final NumberFormat nf;
    /**
     * Creates new form LoginFrame
     * @throws java.io.IOException
     */
    public LoginFrame() throws IOException {
        initComponents();
        setLookAndFeel("Windows");        
        setLocation();
        setIcon();
        this.nf = NumberFormat.getNumberInstance();
    }
    
    private void setLocation() {
        this.setLocationRelativeTo(null);
    }

    private void setIcon() throws IOException {
        setIconImage(Toolkit.getDefaultToolkit().getImage("res\\32x32.png"));
    }

    //configura o look and feel do form
    private void setLookAndFeel(String name){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (name.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Retorna o valor da string source como float.
     * @param source String cujo valor será transformado em float.
     * @return
     * @throws ParseException 
     */
    private float toFloat(String source) throws ParseException {
        return nf.parse(source).floatValue();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        welcome_panel = new javax.swing.JPanel();
        welcome_label = new javax.swing.JLabel();
        form_panel = new javax.swing.JPanel();
        name_label = new javax.swing.JLabel();
        name_field = new javax.swing.JTextField();
        renda_label = new javax.swing.JLabel();
        renda_field = new javax.swing.JFormattedTextField();
        login_button = new javax.swing.JButton();
        tip_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(55, 68, 138));
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(400, 300));
        setName("first_run_frame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(400, 300));

        welcome_panel.setBackground(getBackground());
        welcome_panel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        welcome_label.setFont(welcome_panel.getFont());
        welcome_label.setForeground(new java.awt.Color(255, 255, 255));
        welcome_label.setText("Bem Vindo");
        welcome_panel.add(welcome_label);

        getContentPane().add(welcome_panel, java.awt.BorderLayout.PAGE_START);

        form_panel.setBackground(getBackground());
        form_panel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        java.awt.GridBagLayout form_panelLayout = new java.awt.GridBagLayout();
        form_panelLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        form_panelLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0};
        form_panel.setLayout(form_panelLayout);

        name_label.setFont(form_panel.getFont());
        name_label.setForeground(new java.awt.Color(255, 255, 255));
        name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_label.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 30;
        form_panel.add(name_label, gridBagConstraints);

        name_field.setFont(form_panel.getFont());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        form_panel.add(name_field, gridBagConstraints);

        renda_label.setFont(form_panel.getFont());
        renda_label.setForeground(new java.awt.Color(255, 255, 255));
        renda_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        renda_label.setText("Renda");
        renda_label.setToolTipText("Quanto você ganha, em média, por mês");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        form_panel.add(renda_label, gridBagConstraints);

        renda_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        renda_field.setFont(form_panel.getFont());
        renda_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                renda_fieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        form_panel.add(renda_field, gridBagConstraints);

        login_button.setFont(form_panel.getFont());
        login_button.setText("Entrar");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        form_panel.add(login_button, gridBagConstraints);

        getContentPane().add(form_panel, java.awt.BorderLayout.CENTER);

        tip_panel.setBackground(getBackground());
        tip_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, form_panel.getFont(), new java.awt.Color(255, 255, 255)));
        tip_panel.setForeground(new java.awt.Color(0, 255, 255));

        jLabel2.setFont(form_panel.getFont());
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Todo dia primeiro a sua renda será adicionada à seu saldo.");

        javax.swing.GroupLayout tip_panelLayout = new javax.swing.GroupLayout(tip_panel);
        tip_panel.setLayout(tip_panelLayout);
        tip_panelLayout.setHorizontalGroup(
            tip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tip_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tip_panelLayout.setVerticalGroup(
            tip_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tip_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(tip_panel, java.awt.BorderLayout.PAGE_END);

        getAccessibleContext().setAccessibleName("Login Panel\n");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        if(name_field.getText().isEmpty() || renda_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios.");
        }
        else {
            Sistema.setNome(name_field.getText());           
            try {
                Sistema.setRenda(toFloat(renda_field.getText()));
                Sistema.setSaldo(Sistema.getRenda());
                Sistema.setLoginDate(Sistema.HOJE);
                new MainFrame().setVisible(true);
            } catch (IOException | ParseException ex) {
                Logger.getLogger(LoginFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void renda_fieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_renda_fieldKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            login_button.doClick();
        }
    }//GEN-LAST:event_renda_fieldKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel form_panel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_button;
    private javax.swing.JTextField name_field;
    private javax.swing.JLabel name_label;
    private javax.swing.JFormattedTextField renda_field;
    private javax.swing.JLabel renda_label;
    private javax.swing.JPanel tip_panel;
    private javax.swing.JLabel welcome_label;
    private javax.swing.JPanel welcome_panel;
    // End of variables declaration//GEN-END:variables
}
