/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Toolkit;
import main_system.ContaParcelada;
import main_system.Sistema;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.text.NumberFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main_system.Conta;
import main_system.Tipo;

/**
 *
 * @author ikaro
 */
public class NovaConta extends javax.swing.JFrame {

    private final MainFrame caller;
    private final SimpleDateFormat sdf;
    private final NumberFormat nf;
    private final DefaultTableModel model;
    /**
     * Creates new form NovaConta
     * @param caller Instância do MainFrame que criou este frame.
     * @throws java.io.IOException
     */
    public NovaConta(MainFrame caller) throws IOException {
        this.caller = caller;
        initComponents();
        setLookAndFeel("Windows");
        setLocation();
        setIcon();
        this.nf = NumberFormat.getNumberInstance();
        this.sdf = new SimpleDateFormat(Sistema.DATE_FORMAT); 
        this.model = (DefaultTableModel) caller.getTable().getModel();
    }
    
    /**
     * Define que o frame deve ser aberto no centro da tela.
     */
    private void setLocation() {
        this.setLocationRelativeTo(null);
    }
    
    /**
     * Define o ícone do frame.
     * @throws IOException 
     */
    private void setIcon() throws IOException {
        setIconImage(Toolkit.getDefaultToolkit().getImage("res/32x32.png"));
    }
    
    /**
     * Define qual o estilo que será usado pelo frame.
     * @param name Nome do estilo usado.
     */
    private void setLookAndFeel(String name){
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (name.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private float toFloat(String source) throws ParseException {
        return nf.parse(source).floatValue();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        types_button_group = new javax.swing.ButtonGroup();
        form_panel = new javax.swing.JPanel();
        description_label = new javax.swing.JLabel();
        description_field = new javax.swing.JTextField();
        payday_label = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();
        value_label = new javax.swing.JLabel();
        value_field = new javax.swing.JTextField();
        type_label = new javax.swing.JLabel();
        parcelada_radbutton = new javax.swing.JRadioButton();
        fixa_radbutton = new javax.swing.JRadioButton();
        ammount_field = new javax.swing.JTextField();
        parcelas_label = new javax.swing.JLabel();
        bottom_panel = new javax.swing.JPanel();
        confirm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova Conta");
        setBackground(new java.awt.Color(55, 68, 138));
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);

        form_panel.setBackground(getBackground());
        form_panel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        java.awt.GridBagLayout form_panelLayout = new java.awt.GridBagLayout();
        form_panelLayout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0};
        form_panelLayout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        form_panel.setLayout(form_panelLayout);

        description_label.setFont(form_panel.getFont());
        description_label.setForeground(new java.awt.Color(255, 255, 255));
        description_label.setText("Descrição");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        form_panel.add(description_label, gridBagConstraints);

        description_field.setFont(form_panel.getFont());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        form_panel.add(description_field, gridBagConstraints);

        payday_label.setFont(form_panel.getFont());
        payday_label.setForeground(new java.awt.Color(255, 255, 255));
        payday_label.setText("Data");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        form_panel.add(payday_label, gridBagConstraints);

        calendar.setFont(form_panel.getFont());
        calendar.setMinSelectableDate(caller.getMinData());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        form_panel.add(calendar, gridBagConstraints);

        value_label.setFont(form_panel.getFont());
        value_label.setForeground(new java.awt.Color(255, 255, 255));
        value_label.setText("Valor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        form_panel.add(value_label, gridBagConstraints);

        value_field.setFont(form_panel.getFont());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        form_panel.add(value_field, gridBagConstraints);

        type_label.setFont(form_panel.getFont());
        type_label.setForeground(new java.awt.Color(255, 255, 255));
        type_label.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        form_panel.add(type_label, gridBagConstraints);

        parcelada_radbutton.setBackground(getBackground());
        types_button_group.add(parcelada_radbutton);
        parcelada_radbutton.setFont(form_panel.getFont());
        parcelada_radbutton.setForeground(new java.awt.Color(255, 255, 255));
        parcelada_radbutton.setText("Parcelada");
        parcelada_radbutton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                parcelada_radbuttonItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        form_panel.add(parcelada_radbutton, gridBagConstraints);

        fixa_radbutton.setBackground(getBackground());
        types_button_group.add(fixa_radbutton);
        fixa_radbutton.setFont(form_panel.getFont());
        fixa_radbutton.setForeground(new java.awt.Color(255, 255, 255));
        fixa_radbutton.setText("Fixa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        form_panel.add(fixa_radbutton, gridBagConstraints);

        ammount_field.setFont(form_panel.getFont());
        ammount_field.setToolTipText("quantidade de parcelas");
        ammount_field.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        form_panel.add(ammount_field, gridBagConstraints);

        parcelas_label.setFont(form_panel.getFont());
        parcelas_label.setForeground(new java.awt.Color(255, 255, 255));
        parcelas_label.setText("Parcelas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        form_panel.add(parcelas_label, gridBagConstraints);

        getContentPane().add(form_panel, java.awt.BorderLayout.CENTER);

        bottom_panel.setBackground(getBackground());
        bottom_panel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        confirm.setFont(bottom_panel.getFont());
        confirm.setText("Confirmar");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bottom_panelLayout = new javax.swing.GroupLayout(bottom_panel);
        bottom_panel.setLayout(bottom_panelLayout);
        bottom_panelLayout.setHorizontalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottom_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirm)
                .addContainerGap())
        );
        bottom_panelLayout.setVerticalGroup(
            bottom_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottom_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(confirm)
                .addContainerGap())
        );

        getContentPane().add(bottom_panel, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parcelada_radbuttonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_parcelada_radbuttonItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            ammount_field.setEnabled(true);
        }
    }//GEN-LAST:event_parcelada_radbuttonItemStateChanged

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        Date date = calendar.getDate();
        String desc = description_field.getText();
        String str_date = new SimpleDateFormat(Sistema.DATE_FORMAT).format(date);
        String str_val = value_field.getText();
        float val = 0;
        
        try {
            val = toFloat(str_val);
        } catch (ParseException ex) {
            Logger.getLogger(NovaConta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(desc.isEmpty() || str_date.isEmpty() || str_val.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos os campos são obrigatórios.");
        }
        else {
            String tipo = "";
            
            //se o usuário escolheu criar uma conta parcelada
            if(parcelada_radbutton.isSelected()) {
                int parcelas = Integer.parseInt(ammount_field.getText());
                ContaParcelada nova = new ContaParcelada(desc, date, val, parcelas, false);
                nova.gerarParcelas(date, parcelas, val);
                nova.setParcelaAtual();
                Sistema.adicionarConta(nova);
                caller.addRow(new Object[] {
                    model.getRowCount()+1, desc, str_date, val, Tipo.P.getText(), parcelas
                });
                caller.addIndice(Sistema.buscarConta(nova));
                caller.setSaldoLabel();
                this.dispose();
                return;
            }
            
            Conta nova = null;
            if(fixa_radbutton.isSelected()) {
                tipo = Tipo.F.getText();
            }
            else {
                tipo = Tipo.N.getText();
            }
            nova = new Conta(desc, date, val, tipo, false); 
            Sistema.adicionarConta(nova);
            caller.addRow(new Object[] {
                model.getRowCount()+1, desc, str_date, val, tipo, 0
            });
            caller.addIndice(Sistema.buscarConta(nova));
            caller.setSaldoLabel();
            this.dispose();
        }
    }//GEN-LAST:event_confirmActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ammount_field;
    private javax.swing.JPanel bottom_panel;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField description_field;
    private javax.swing.JLabel description_label;
    private javax.swing.JRadioButton fixa_radbutton;
    private javax.swing.JPanel form_panel;
    private javax.swing.JRadioButton parcelada_radbutton;
    private javax.swing.JLabel parcelas_label;
    private javax.swing.JLabel payday_label;
    private javax.swing.JLabel type_label;
    private javax.swing.ButtonGroup types_button_group;
    private javax.swing.JTextField value_field;
    private javax.swing.JLabel value_label;
    // End of variables declaration//GEN-END:variables
}
